// ignore_for_file: unused_element, unused_field
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for the SentinelLibrary.
class SentinelLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SentinelLibrary(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SentinelLibrary.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void __va_start(ffi.Pointer<va_list> arg0) {
    return ___va_start(arg0);
  }

  late final ___va_startPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<va_list>)>>(
        '__va_start',
      );
  late final ___va_start = ___va_startPtr
      .asFunction<void Function(ffi.Pointer<va_list>)>();

  void __security_init_cookie() {
    return ___security_init_cookie();
  }

  late final ___security_init_cookiePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        '__security_init_cookie',
      );
  late final ___security_init_cookie = ___security_init_cookiePtr
      .asFunction<void Function()>();

  void __security_check_cookie(int _StackCookie) {
    return ___security_check_cookie(_StackCookie);
  }

  late final ___security_check_cookiePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
        '__security_check_cookie',
      );
  late final ___security_check_cookie = ___security_check_cookiePtr
      .asFunction<void Function(int)>();

  void __report_gsfailure(int _StackCookie) {
    return ___report_gsfailure(_StackCookie);
  }

  late final ___report_gsfailurePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
        '__report_gsfailure',
      );
  late final ___report_gsfailure = ___report_gsfailurePtr
      .asFunction<void Function(int)>();

  late final ffi.Pointer<ffi.UintPtr> ___security_cookie = _lookup<ffi.UintPtr>(
    '__security_cookie',
  );

  int get __security_cookie => ___security_cookie.value;

  set __security_cookie(int value) => ___security_cookie.value = value;

  void _invalid_parameter_noinfo() {
    return __invalid_parameter_noinfo();
  }

  late final __invalid_parameter_noinfoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        '_invalid_parameter_noinfo',
      );
  late final __invalid_parameter_noinfo = __invalid_parameter_noinfoPtr
      .asFunction<void Function()>();

  void _invalid_parameter_noinfo_noreturn() {
    return __invalid_parameter_noinfo_noreturn();
  }

  late final __invalid_parameter_noinfo_noreturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        '_invalid_parameter_noinfo_noreturn',
      );
  late final __invalid_parameter_noinfo_noreturn =
      __invalid_parameter_noinfo_noreturnPtr.asFunction<void Function()>();

  void _invoke_watson(
    ffi.Pointer<ffi.WChar> _Expression,
    ffi.Pointer<ffi.WChar> _FunctionName,
    ffi.Pointer<ffi.WChar> _FileName,
    int _LineNo,
    int _Reserved,
  ) {
    return __invoke_watson(
      _Expression,
      _FunctionName,
      _FileName,
      _LineNo,
      _Reserved,
    );
  }

  late final __invoke_watsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.WChar>,
            ffi.UnsignedInt,
            ffi.UintPtr,
          )
        >
      >('_invoke_watson');
  late final __invoke_watson = __invoke_watsonPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.WChar>,
          int,
          int,
        )
      >();

  ffi.Pointer<ffi.Int> _errno() {
    return __errno();
  }

  late final __errnoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int> Function()>>('_errno');
  late final __errno = __errnoPtr.asFunction<ffi.Pointer<ffi.Int> Function()>();

  int _set_errno(int _Value) {
    return __set_errno(_Value);
  }

  late final __set_errnoPtr =
      _lookup<ffi.NativeFunction<errno_t Function(ffi.Int)>>('_set_errno');
  late final __set_errno = __set_errnoPtr.asFunction<int Function(int)>();

  int _get_errno(ffi.Pointer<ffi.Int> _Value) {
    return __get_errno(_Value);
  }

  late final __get_errnoPtr =
      _lookup<ffi.NativeFunction<errno_t Function(ffi.Pointer<ffi.Int>)>>(
        '_get_errno',
      );
  late final __get_errno = __get_errnoPtr
      .asFunction<int Function(ffi.Pointer<ffi.Int>)>();

  int __threadid() {
    return ___threadid();
  }

  late final ___threadidPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedLong Function()>>('__threadid');
  late final ___threadid = ___threadidPtr.asFunction<int Function()>();

  int __threadhandle() {
    return ___threadhandle();
  }

  late final ___threadhandlePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function()>>('__threadhandle');
  late final ___threadhandle = ___threadhandlePtr.asFunction<int Function()>();

  int _GoStringLen(_GoString_ s) {
    return __GoStringLen(s);
  }

  late final __GoStringLenPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(_GoString_)>>(
        '_GoStringLen',
      );
  late final __GoStringLen = __GoStringLenPtr
      .asFunction<int Function(_GoString_)>();

  ffi.Pointer<ffi.Char> _GoStringPtr(_GoString_ s) {
    return __GoStringPtr(s);
  }

  late final __GoStringPtrPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>>(
        '_GoStringPtr',
      );
  late final __GoStringPtr = __GoStringPtrPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>();

  double cabs(_Dcomplex _Z) {
    return _cabs(_Z);
  }

  late final _cabsPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(_Dcomplex)>>('cabs');
  late final _cabs = _cabsPtr.asFunction<double Function(_Dcomplex)>();

  _Dcomplex cacos(_Dcomplex _Z) {
    return _cacos(_Z);
  }

  late final _cacosPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('cacos');
  late final _cacos = _cacosPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex cacosh(_Dcomplex _Z) {
    return _cacosh(_Z);
  }

  late final _cacoshPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('cacosh');
  late final _cacosh = _cacoshPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  double carg(_Dcomplex _Z) {
    return _carg(_Z);
  }

  late final _cargPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(_Dcomplex)>>('carg');
  late final _carg = _cargPtr.asFunction<double Function(_Dcomplex)>();

  _Dcomplex casin(_Dcomplex _Z) {
    return _casin(_Z);
  }

  late final _casinPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('casin');
  late final _casin = _casinPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex casinh(_Dcomplex _Z) {
    return _casinh(_Z);
  }

  late final _casinhPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('casinh');
  late final _casinh = _casinhPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex catan(_Dcomplex _Z) {
    return _catan(_Z);
  }

  late final _catanPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('catan');
  late final _catan = _catanPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex catanh(_Dcomplex _Z) {
    return _catanh(_Z);
  }

  late final _catanhPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('catanh');
  late final _catanh = _catanhPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex ccos(_Dcomplex _Z) {
    return _ccos(_Z);
  }

  late final _ccosPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('ccos');
  late final _ccos = _ccosPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex ccosh(_Dcomplex _Z) {
    return _ccosh(_Z);
  }

  late final _ccoshPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('ccosh');
  late final _ccosh = _ccoshPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex cexp(_Dcomplex _Z) {
    return _cexp(_Z);
  }

  late final _cexpPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('cexp');
  late final _cexp = _cexpPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  double cimag(_Dcomplex _Z) {
    return _cimag(_Z);
  }

  late final _cimagPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(_Dcomplex)>>('cimag');
  late final _cimag = _cimagPtr.asFunction<double Function(_Dcomplex)>();

  _Dcomplex clog(_Dcomplex _Z) {
    return _clog(_Z);
  }

  late final _clogPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('clog');
  late final _clog = _clogPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex clog10(_Dcomplex _Z) {
    return _clog10(_Z);
  }

  late final _clog10Ptr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('clog10');
  late final _clog10 = _clog10Ptr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex conj(_Dcomplex _Z) {
    return _conj(_Z);
  }

  late final _conjPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('conj');
  late final _conj = _conjPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex cpow(_Dcomplex _X, _Dcomplex _Y) {
    return _cpow(_X, _Y);
  }

  late final _cpowPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex, _Dcomplex)>>(
        'cpow',
      );
  late final _cpow = _cpowPtr
      .asFunction<_Dcomplex Function(_Dcomplex, _Dcomplex)>();

  _Dcomplex cproj(_Dcomplex _Z) {
    return _cproj(_Z);
  }

  late final _cprojPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('cproj');
  late final _cproj = _cprojPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  double creal(_Dcomplex _Z) {
    return _creal(_Z);
  }

  late final _crealPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(_Dcomplex)>>('creal');
  late final _creal = _crealPtr.asFunction<double Function(_Dcomplex)>();

  _Dcomplex csin(_Dcomplex _Z) {
    return _csin(_Z);
  }

  late final _csinPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('csin');
  late final _csin = _csinPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex csinh(_Dcomplex _Z) {
    return _csinh(_Z);
  }

  late final _csinhPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('csinh');
  late final _csinh = _csinhPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex csqrt(_Dcomplex _Z) {
    return _csqrt(_Z);
  }

  late final _csqrtPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('csqrt');
  late final _csqrt = _csqrtPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex ctan(_Dcomplex _Z) {
    return _ctan(_Z);
  }

  late final _ctanPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('ctan');
  late final _ctan = _ctanPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  _Dcomplex ctanh(_Dcomplex _Z) {
    return _ctanh(_Z);
  }

  late final _ctanhPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex)>>('ctanh');
  late final _ctanh = _ctanhPtr.asFunction<_Dcomplex Function(_Dcomplex)>();

  double norm(_Dcomplex _Z) {
    return _norm(_Z);
  }

  late final _normPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(_Dcomplex)>>('norm');
  late final _norm = _normPtr.asFunction<double Function(_Dcomplex)>();

  double cabsf(_Fcomplex _Z) {
    return _cabsf(_Z);
  }

  late final _cabsfPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(_Fcomplex)>>('cabsf');
  late final _cabsf = _cabsfPtr.asFunction<double Function(_Fcomplex)>();

  _Fcomplex cacosf(_Fcomplex _Z) {
    return _cacosf(_Z);
  }

  late final _cacosfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('cacosf');
  late final _cacosf = _cacosfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex cacoshf(_Fcomplex _Z) {
    return _cacoshf(_Z);
  }

  late final _cacoshfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('cacoshf');
  late final _cacoshf = _cacoshfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  double cargf(_Fcomplex _Z) {
    return _cargf(_Z);
  }

  late final _cargfPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(_Fcomplex)>>('cargf');
  late final _cargf = _cargfPtr.asFunction<double Function(_Fcomplex)>();

  _Fcomplex casinf(_Fcomplex _Z) {
    return _casinf(_Z);
  }

  late final _casinfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('casinf');
  late final _casinf = _casinfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex casinhf(_Fcomplex _Z) {
    return _casinhf(_Z);
  }

  late final _casinhfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('casinhf');
  late final _casinhf = _casinhfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex catanf(_Fcomplex _Z) {
    return _catanf(_Z);
  }

  late final _catanfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('catanf');
  late final _catanf = _catanfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex catanhf(_Fcomplex _Z) {
    return _catanhf(_Z);
  }

  late final _catanhfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('catanhf');
  late final _catanhf = _catanhfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex ccosf(_Fcomplex _Z) {
    return _ccosf(_Z);
  }

  late final _ccosfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('ccosf');
  late final _ccosf = _ccosfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex ccoshf(_Fcomplex _Z) {
    return _ccoshf(_Z);
  }

  late final _ccoshfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('ccoshf');
  late final _ccoshf = _ccoshfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex cexpf(_Fcomplex _Z) {
    return _cexpf(_Z);
  }

  late final _cexpfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('cexpf');
  late final _cexpf = _cexpfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  double cimagf(_Fcomplex _Z) {
    return _cimagf(_Z);
  }

  late final _cimagfPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(_Fcomplex)>>('cimagf');
  late final _cimagf = _cimagfPtr.asFunction<double Function(_Fcomplex)>();

  _Fcomplex clogf(_Fcomplex _Z) {
    return _clogf(_Z);
  }

  late final _clogfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('clogf');
  late final _clogf = _clogfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex clog10f(_Fcomplex _Z) {
    return _clog10f(_Z);
  }

  late final _clog10fPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('clog10f');
  late final _clog10f = _clog10fPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex conjf(_Fcomplex _Z) {
    return _conjf(_Z);
  }

  late final _conjfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('conjf');
  late final _conjf = _conjfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex cpowf(_Fcomplex _X, _Fcomplex _Y) {
    return _cpowf(_X, _Y);
  }

  late final _cpowfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex, _Fcomplex)>>(
        'cpowf',
      );
  late final _cpowf = _cpowfPtr
      .asFunction<_Fcomplex Function(_Fcomplex, _Fcomplex)>();

  _Fcomplex cprojf(_Fcomplex _Z) {
    return _cprojf(_Z);
  }

  late final _cprojfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('cprojf');
  late final _cprojf = _cprojfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  double crealf(_Fcomplex _Z) {
    return _crealf(_Z);
  }

  late final _crealfPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(_Fcomplex)>>('crealf');
  late final _crealf = _crealfPtr.asFunction<double Function(_Fcomplex)>();

  _Fcomplex csinf(_Fcomplex _Z) {
    return _csinf(_Z);
  }

  late final _csinfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('csinf');
  late final _csinf = _csinfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex csinhf(_Fcomplex _Z) {
    return _csinhf(_Z);
  }

  late final _csinhfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('csinhf');
  late final _csinhf = _csinhfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex csqrtf(_Fcomplex _Z) {
    return _csqrtf(_Z);
  }

  late final _csqrtfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('csqrtf');
  late final _csqrtf = _csqrtfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex ctanf(_Fcomplex _Z) {
    return _ctanf(_Z);
  }

  late final _ctanfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('ctanf');
  late final _ctanf = _ctanfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  _Fcomplex ctanhf(_Fcomplex _Z) {
    return _ctanhf(_Z);
  }

  late final _ctanhfPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex)>>('ctanhf');
  late final _ctanhf = _ctanhfPtr.asFunction<_Fcomplex Function(_Fcomplex)>();

  double normf(_Fcomplex _Z) {
    return _normf(_Z);
  }

  late final _normfPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(_Fcomplex)>>('normf');
  late final _normf = _normfPtr.asFunction<double Function(_Fcomplex)>();

  _Dcomplex _Cbuild(double _Re, double _Im) {
    return __Cbuild(_Re, _Im);
  }

  late final __CbuildPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(ffi.Double, ffi.Double)>>(
        '_Cbuild',
      );
  late final __Cbuild = __CbuildPtr
      .asFunction<_Dcomplex Function(double, double)>();

  _Dcomplex _Cmulcc(_Dcomplex _X, _Dcomplex _Y) {
    return __Cmulcc(_X, _Y);
  }

  late final __CmulccPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex, _Dcomplex)>>(
        '_Cmulcc',
      );
  late final __Cmulcc = __CmulccPtr
      .asFunction<_Dcomplex Function(_Dcomplex, _Dcomplex)>();

  _Dcomplex _Cmulcr(_Dcomplex _X, double _Y) {
    return __Cmulcr(_X, _Y);
  }

  late final __CmulcrPtr =
      _lookup<ffi.NativeFunction<_Dcomplex Function(_Dcomplex, ffi.Double)>>(
        '_Cmulcr',
      );
  late final __Cmulcr = __CmulcrPtr
      .asFunction<_Dcomplex Function(_Dcomplex, double)>();

  _Fcomplex _FCbuild(double _Re, double _Im) {
    return __FCbuild(_Re, _Im);
  }

  late final __FCbuildPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(ffi.Float, ffi.Float)>>(
        '_FCbuild',
      );
  late final __FCbuild = __FCbuildPtr
      .asFunction<_Fcomplex Function(double, double)>();

  _Fcomplex _FCmulcc(_Fcomplex _X, _Fcomplex _Y) {
    return __FCmulcc(_X, _Y);
  }

  late final __FCmulccPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex, _Fcomplex)>>(
        '_FCmulcc',
      );
  late final __FCmulcc = __FCmulccPtr
      .asFunction<_Fcomplex Function(_Fcomplex, _Fcomplex)>();

  _Fcomplex _FCmulcr(_Fcomplex _X, double _Y) {
    return __FCmulcr(_X, _Y);
  }

  late final __FCmulcrPtr =
      _lookup<ffi.NativeFunction<_Fcomplex Function(_Fcomplex, ffi.Float)>>(
        '_FCmulcr',
      );
  late final __FCmulcr = __FCmulcrPtr
      .asFunction<_Fcomplex Function(_Fcomplex, double)>();

  void RegisterPort(int port) {
    return _RegisterPort(port);
  }

  late final _RegisterPortPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>(
        'RegisterPort',
      );
  late final _RegisterPort = _RegisterPortPtr.asFunction<void Function(int)>();

  void UnregisterPort() {
    return _UnregisterPort();
  }

  late final _UnregisterPortPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('UnregisterPort');
  late final _UnregisterPort = _UnregisterPortPtr.asFunction<void Function()>();

  void BridgeInit(ffi.Pointer<ffi.Void> api) {
    return _BridgeInit(api);
  }

  late final _BridgeInitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'BridgeInit',
      );
  late final _BridgeInit =
      _BridgeInitPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void Move(int x, int y, int port) {
    return _Move(x, y, port);
  }

  late final _MovePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.LongLong)>
      >('Move');
  late final _Move = _MovePtr.asFunction<void Function(int, int, int)>();

  void MoveRelative(int x, int y, int port) {
    return _MoveRelative(x, y, port);
  }

  late final _MoveRelativePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.LongLong)>
      >('MoveRelative');
  late final _MoveRelative =
      _MoveRelativePtr.asFunction<void Function(int, int, int)>();

  void Click(ffi.Pointer<ffi.Char> btn, int dbl, int port) {
    return _Click(btn, dbl, port);
  }

  late final _ClickPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.LongLong)
        >
      >('Click');
  late final _Click =
      _ClickPtr.asFunction<void Function(ffi.Pointer<ffi.Char>, int, int)>();

  void Toggle(ffi.Pointer<ffi.Char> btn, ffi.Pointer<ffi.Char> dir, int port) {
    return _Toggle(btn, dir, port);
  }

  late final _TogglePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('Toggle');
  late final _Toggle =
      _TogglePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void Scroll(int x, int y, int port) {
    return _Scroll(x, y, port);
  }

  late final _ScrollPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.LongLong)>
      >('Scroll');
  late final _Scroll = _ScrollPtr.asFunction<void Function(int, int, int)>();

  void ScrollDir(int amount, ffi.Pointer<ffi.Char> dir, int port) {
    return _ScrollDir(amount, dir, port);
  }

  late final _ScrollDirPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('ScrollDir');
  late final _ScrollDir =
      _ScrollDirPtr.asFunction<
        void Function(int, ffi.Pointer<ffi.Char>, int)
      >();

  void GetLocation(int port) {
    return _GetLocation(port);
  }

  late final _GetLocationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>(
        'GetLocation',
      );
  late final _GetLocation = _GetLocationPtr.asFunction<void Function(int)>();

  void SetMouseSleep(int ms, int port) {
    return _SetMouseSleep(ms, port);
  }

  late final _SetMouseSleepPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'SetMouseSleep',
      );
  late final _SetMouseSleep =
      _SetMouseSleepPtr.asFunction<void Function(int, int)>();

  void MilliSleep(int ms, int port) {
    return _MilliSleep(ms, port);
  }

  late final _MilliSleepPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'MilliSleep',
      );
  late final _MilliSleep = _MilliSleepPtr.asFunction<void Function(int, int)>();

  void StopTask(int taskID, int port) {
    return _StopTask(taskID, port);
  }

  late final _StopTaskPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.LongLong, ffi.LongLong)>
      >('StopTask');
  late final _StopTask = _StopTaskPtr.asFunction<void Function(int, int)>();

  int MoveSmoothStart(int x, int y, int port) {
    return _MoveSmoothStart(x, y, port);
  }

  late final _MoveSmoothStartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('MoveSmoothStart');
  late final _MoveSmoothStart =
      _MoveSmoothStartPtr.asFunction<int Function(int, int, int)>();

  int DragSmoothStart(int x, int y, int port) {
    return _DragSmoothStart(x, y, port);
  }

  late final _DragSmoothStartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('DragSmoothStart');
  late final _DragSmoothStart =
      _DragSmoothStartPtr.asFunction<int Function(int, int, int)>();

  int ScrollSmoothStart(int x, int y, int port) {
    return _ScrollSmoothStart(x, y, port);
  }

  late final _ScrollSmoothStartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('ScrollSmoothStart');
  late final _ScrollSmoothStart =
      _ScrollSmoothStartPtr.asFunction<int Function(int, int, int)>();

  void TypeStr(ffi.Pointer<ffi.Char> text, int port) {
    return _TypeStr(text, port);
  }

  late final _TypeStrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('TypeStr');
  late final _TypeStr =
      _TypeStrPtr.asFunction<void Function(ffi.Pointer<ffi.Char>, int)>();

  void TypeStrWithInts(
    ffi.Pointer<ffi.Char> text,
    int arg1,
    int arg2,
    int port,
  ) {
    return _TypeStrWithInts(text, arg1, arg2, port);
  }

  late final _TypeStrWithIntsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
            ffi.LongLong,
          )
        >
      >('TypeStrWithInts');
  late final _TypeStrWithInts =
      _TypeStrWithIntsPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int, int, int)
      >();

  void GoSleep(int seconds, int port) {
    return _GoSleep(seconds, port);
  }

  late final _GoSleepPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'GoSleep',
      );
  late final _GoSleep = _GoSleepPtr.asFunction<void Function(int, int)>();

  void SetKeySleep(int ms, int port) {
    return _SetKeySleep(ms, port);
  }

  late final _SetKeySleepPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'SetKeySleep',
      );
  late final _SetKeySleep =
      _SetKeySleepPtr.asFunction<void Function(int, int)>();

  void KeyTap(ffi.Pointer<ffi.Char> key, ffi.Pointer<ffi.Char> mods, int port) {
    return _KeyTap(key, mods, port);
  }

  late final _KeyTapPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('KeyTap');
  late final _KeyTap =
      _KeyTapPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void KeyTapArr(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> modsJson,
    int port,
  ) {
    return _KeyTapArr(key, modsJson, port);
  }

  late final _KeyTapArrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('KeyTapArr');
  late final _KeyTapArr =
      _KeyTapArrPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void KeyToggle(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> direction,
    int port,
  ) {
    return _KeyToggle(key, direction, port);
  }

  late final _KeyTogglePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('KeyToggle');
  late final _KeyToggle =
      _KeyTogglePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void WriteAll(ffi.Pointer<ffi.Char> text, int port) {
    return _WriteAll(text, port);
  }

  late final _WriteAllPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('WriteAll');
  late final _WriteAll =
      _WriteAllPtr.asFunction<void Function(ffi.Pointer<ffi.Char>, int)>();

  void ReadAll(int port) {
    return _ReadAll(port);
  }

  late final _ReadAllPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>('ReadAll');
  late final _ReadAll = _ReadAllPtr.asFunction<void Function(int)>();

  int TypeStrStart(ffi.Pointer<ffi.Char> text, int port) {
    return _TypeStrStart(text, port);
  }

  late final _TypeStrStartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('TypeStrStart');
  late final _TypeStrStart =
      _TypeStrStartPtr.asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  void GetPixelColor(int x, int y, int port) {
    return _GetPixelColor(x, y, port);
  }

  late final _GetPixelColorPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.LongLong)>
      >('GetPixelColor');
  late final _GetPixelColor =
      _GetPixelColorPtr.asFunction<void Function(int, int, int)>();

  void GetScreenSize(int port) {
    return _GetScreenSize(port);
  }

  late final _GetScreenSizePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>(
        'GetScreenSize',
      );
  late final _GetScreenSize =
      _GetScreenSizePtr.asFunction<void Function(int)>();

  void CaptureScreenSave(
    int x,
    int y,
    int w,
    int h,
    ffi.Pointer<ffi.Char> path,
    int port,
  ) {
    return _CaptureScreenSave(x, y, w, h, path, port);
  }

  late final _CaptureScreenSavePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('CaptureScreenSave');
  late final _CaptureScreenSave =
      _CaptureScreenSavePtr.asFunction<
        void Function(int, int, int, int, ffi.Pointer<ffi.Char>, int)
      >();

  void CaptureScreenBase64(int x, int y, int w, int h, int port) {
    return _CaptureScreenBase64(x, y, w, h, port);
  }

  late final _CaptureScreenBase64Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('CaptureScreenBase64');
  late final _CaptureScreenBase64 =
      _CaptureScreenBase64Ptr.asFunction<
        void Function(int, int, int, int, int)
      >();

  void DisplaysNum(int port) {
    return _DisplaysNum(port);
  }

  late final _DisplaysNumPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>(
        'DisplaysNum',
      );
  late final _DisplaysNum = _DisplaysNumPtr.asFunction<void Function(int)>();

  void GetDisplayBounds(int index, int port) {
    return _GetDisplayBounds(index, port);
  }

  late final _GetDisplayBoundsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'GetDisplayBounds',
      );
  late final _GetDisplayBounds =
      _GetDisplayBoundsPtr.asFunction<void Function(int, int)>();

  void CaptureDisplaySave(int index, ffi.Pointer<ffi.Char> path, int port) {
    return _CaptureDisplaySave(index, path, port);
  }

  late final _CaptureDisplaySavePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('CaptureDisplaySave');
  late final _CaptureDisplaySave =
      _CaptureDisplaySavePtr.asFunction<
        void Function(int, ffi.Pointer<ffi.Char>, int)
      >();

  void CaptureDisplayRegionSave(
    int index,
    int x,
    int y,
    int w,
    int h,
    ffi.Pointer<ffi.Char> path,
    int port,
  ) {
    return _CaptureDisplayRegionSave(index, x, y, w, h, path, port);
  }

  late final _CaptureDisplayRegionSavePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('CaptureDisplayRegionSave');
  late final _CaptureDisplayRegionSave =
      _CaptureDisplayRegionSavePtr.asFunction<
        void Function(int, int, int, int, int, ffi.Pointer<ffi.Char>, int)
      >();

  void SaveImageJpeg(ffi.Pointer<ffi.Char> path, int quality, int port) {
    return _SaveImageJpeg(path, quality, port);
  }

  late final _SaveImageJpegPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.LongLong)
        >
      >('SaveImageJpeg');
  late final _SaveImageJpeg =
      _SaveImageJpegPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int, int)
      >();

  void SaveImagePNGFromCaptureImg(ffi.Pointer<ffi.Char> path, int port) {
    return _SaveImagePNGFromCaptureImg(path, port);
  }

  late final _SaveImagePNGFromCaptureImgPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('SaveImagePNGFromCaptureImg');
  late final _SaveImagePNGFromCaptureImg =
      _SaveImagePNGFromCaptureImgPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void CaptureScreenBitmapSave(
    int x,
    int y,
    int w,
    int h,
    ffi.Pointer<ffi.Char> path,
    int port,
  ) {
    return _CaptureScreenBitmapSave(x, y, w, h, path, port);
  }

  late final _CaptureScreenBitmapSavePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('CaptureScreenBitmapSave');
  late final _CaptureScreenBitmapSave =
      _CaptureScreenBitmapSavePtr.asFunction<
        void Function(int, int, int, int, ffi.Pointer<ffi.Char>, int)
      >();

  void FindBitmapFromCapture(int x, int y, int w, int h, int port) {
    return _FindBitmapFromCapture(x, y, w, h, port);
  }

  late final _FindBitmapFromCapturePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('FindBitmapFromCapture');
  late final _FindBitmapFromCapture =
      _FindBitmapFromCapturePtr.asFunction<
        void Function(int, int, int, int, int)
      >();

  void FindAllBitmapFromCapture(int x, int y, int w, int h, int port) {
    return _FindAllBitmapFromCapture(x, y, w, h, port);
  }

  late final _FindAllBitmapFromCapturePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('FindAllBitmapFromCapture');
  late final _FindAllBitmapFromCapture =
      _FindAllBitmapFromCapturePtr.asFunction<
        void Function(int, int, int, int, int)
      >();

  void MoveToFoundBitmap(int x, int y, int w, int h, int port) {
    return _MoveToFoundBitmap(x, y, w, h, port);
  }

  late final _MoveToFoundBitmapPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('MoveToFoundBitmap');
  late final _MoveToFoundBitmap =
      _MoveToFoundBitmapPtr.asFunction<
        void Function(int, int, int, int, int)
      >();

  void SaveBitmapToFile(
    int x,
    int y,
    int w,
    int h,
    ffi.Pointer<ffi.Char> path,
    int port,
  ) {
    return _SaveBitmapToFile(x, y, w, h, path, port);
  }

  late final _SaveBitmapToFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('SaveBitmapToFile');
  late final _SaveBitmapToFile =
      _SaveBitmapToFilePtr.asFunction<
        void Function(int, int, int, int, ffi.Pointer<ffi.Char>, int)
      >();

  void SaveCaptureRegion(
    ffi.Pointer<ffi.Char> path,
    int x,
    int y,
    int w,
    int h,
    int port,
  ) {
    return _SaveCaptureRegion(path, x, y, w, h, port);
  }

  late final _SaveCaptureRegionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.LongLong,
          )
        >
      >('SaveCaptureRegion');
  late final _SaveCaptureRegion =
      _SaveCaptureRegionPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int, int, int, int, int)
      >();

  void SaveCaptureFull(ffi.Pointer<ffi.Char> path, int port) {
    return _SaveCaptureFull(path, port);
  }

  late final _SaveCaptureFullPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('SaveCaptureFull');
  late final _SaveCaptureFull =
      _SaveCaptureFullPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void BitmapOpenFind(ffi.Pointer<ffi.Char> path, int port) {
    return _BitmapOpenFind(path, port);
  }

  late final _BitmapOpenFindPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('BitmapOpenFind');
  late final _BitmapOpenFind =
      _BitmapOpenFindPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void BitmapFindAllFromFile(ffi.Pointer<ffi.Char> path, int port) {
    return _BitmapFindAllFromFile(path, port);
  }

  late final _BitmapFindAllFromFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('BitmapFindAllFromFile');
  late final _BitmapFindAllFromFile =
      _BitmapFindAllFromFilePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void MoveToFoundFromFile(ffi.Pointer<ffi.Char> path, int port) {
    return _MoveToFoundFromFile(path, port);
  }

  late final _MoveToFoundFromFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('MoveToFoundFromFile');
  late final _MoveToFoundFromFile =
      _MoveToFoundFromFilePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void HookRegisterCombo(
    ffi.Pointer<ffi.Char> mods,
    ffi.Pointer<ffi.Char> key,
    int port,
  ) {
    return _HookRegisterCombo(mods, key, port);
  }

  late final _HookRegisterComboPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('HookRegisterCombo');
  late final _HookRegisterCombo =
      _HookRegisterComboPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void HookStart(int port) {
    return _HookStart(port);
  }

  late final _HookStartPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>('HookStart');
  late final _HookStart = _HookStartPtr.asFunction<void Function(int)>();

  void HookStop() {
    return _HookStop();
  }

  late final _HookStopPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'HookStop',
  );
  late final _HookStop = _HookStopPtr.asFunction<void Function()>();

  void HookAddEvent(ffi.Pointer<ffi.Char> name, int port) {
    return _HookAddEvent(name, port);
  }

  late final _HookAddEventPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('HookAddEvent');
  late final _HookAddEvent =
      _HookAddEventPtr.asFunction<void Function(ffi.Pointer<ffi.Char>, int)>();

  void DecodeAndReportImageSize(ffi.Pointer<ffi.Char> path, int port) {
    return _DecodeAndReportImageSize(path, port);
  }

  late final _DecodeAndReportImageSizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('DecodeAndReportImageSize');
  late final _DecodeAndReportImageSize =
      _DecodeAndReportImageSizePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  int StartMonitor(int port) {
    return _StartMonitor(port);
  }

  late final _StartMonitorPtr =
      _lookup<ffi.NativeFunction<ffi.LongLong Function(ffi.LongLong)>>(
        'StartMonitor',
      );
  late final _StartMonitor = _StartMonitorPtr.asFunction<int Function(int)>();

  void ControlService(
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> action,
    int port,
  ) {
    return _ControlService(name, action, port);
  }

  late final _ControlServicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('ControlService');
  late final _ControlService =
      _ControlServicePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();
}

typedef va_list = ffi.Pointer<ffi.Char>;
typedef ptrdiff_t = ffi.LongLong;
typedef Dartptrdiff_t = int;
typedef errno_t = ffi.Int;
typedef Darterrno_t = int;
typedef wint_t = ffi.UnsignedShort;
typedef Dartwint_t = int;
typedef wctype_t = ffi.UnsignedShort;
typedef Dartwctype_t = int;
typedef __time32_t = ffi.Long;
typedef Dart__time32_t = int;
typedef __time64_t = ffi.LongLong;
typedef Dart__time64_t = int;

final class __crt_locale_data_public extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedShort> _locale_pctype;

  @ffi.Int()
  external int _locale_mb_cur_max;

  @ffi.UnsignedInt()
  external int _locale_lc_codepage;
}

final class __crt_locale_data extends ffi.Opaque {}

final class __crt_multibyte_data extends ffi.Opaque {}

final class __crt_locale_pointers extends ffi.Struct {
  external ffi.Pointer<__crt_locale_data> locinfo;

  external ffi.Pointer<__crt_multibyte_data> mbcinfo;
}

typedef _locale_t = ffi.Pointer<__crt_locale_pointers>;

final class _Mbstatet extends ffi.Struct {
  @ffi.UnsignedLong()
  external int _Wchar;

  @ffi.UnsignedShort()
  external int _Byte;

  @ffi.UnsignedShort()
  external int _State;
}

typedef mbstate_t = _Mbstatet;
typedef time_t = __time64_t;
typedef rsize_t = ffi.Size;
typedef Dartrsize_t = int;

final class _GoString_ extends ffi.Struct {
  external ffi.Pointer<ffi.Char> p;

  @ptrdiff_t()
  external int n;
}

typedef int_least8_t = ffi.SignedChar;
typedef Dartint_least8_t = int;
typedef int_least16_t = ffi.Short;
typedef Dartint_least16_t = int;
typedef int_least32_t = ffi.Int;
typedef Dartint_least32_t = int;
typedef int_least64_t = ffi.LongLong;
typedef Dartint_least64_t = int;
typedef uint_least8_t = ffi.UnsignedChar;
typedef Dartuint_least8_t = int;
typedef uint_least16_t = ffi.UnsignedShort;
typedef Dartuint_least16_t = int;
typedef uint_least32_t = ffi.UnsignedInt;
typedef Dartuint_least32_t = int;
typedef uint_least64_t = ffi.UnsignedLongLong;
typedef Dartuint_least64_t = int;
typedef int_fast8_t = ffi.SignedChar;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Int;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Int;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.LongLong;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.UnsignedChar;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.UnsignedInt;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.UnsignedInt;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.UnsignedLongLong;
typedef Dartuint_fast64_t = int;
typedef intmax_t = ffi.LongLong;
typedef Dartintmax_t = int;
typedef uintmax_t = ffi.UnsignedLongLong;
typedef Dartuintmax_t = int;
typedef GoInt8 = ffi.SignedChar;
typedef DartGoInt8 = int;
typedef GoUint8 = ffi.UnsignedChar;
typedef DartGoUint8 = int;
typedef GoInt16 = ffi.Short;
typedef DartGoInt16 = int;
typedef GoUint16 = ffi.UnsignedShort;
typedef DartGoUint16 = int;
typedef GoInt32 = ffi.Int;
typedef DartGoInt32 = int;
typedef GoUint32 = ffi.UnsignedInt;
typedef DartGoUint32 = int;
typedef GoInt64 = ffi.LongLong;
typedef DartGoInt64 = int;
typedef GoUint64 = ffi.UnsignedLongLong;
typedef DartGoUint64 = int;
typedef GoInt = GoInt64;
typedef GoUint = GoUint64;
typedef GoUintptr = ffi.Size;
typedef DartGoUintptr = int;
typedef GoFloat32 = ffi.Float;
typedef DartGoFloat32 = double;
typedef GoFloat64 = ffi.Double;
typedef DartGoFloat64 = double;

final class _C_double_complex extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Double> _Val;
}

final class _C_float_complex extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Float> _Val;
}

final class _C_ldouble_complex extends ffi.Opaque {}

typedef _Dcomplex = _C_double_complex;
typedef _Fcomplex = _C_float_complex;
typedef _Lcomplex = _C_ldouble_complex;
typedef GoComplex64 = _Fcomplex;
typedef GoComplex128 = _Dcomplex;
typedef GoString = _GoString_;
typedef GoMap = ffi.Pointer<ffi.Void>;
typedef GoChan = ffi.Pointer<ffi.Void>;

final class GoInterface extends ffi.Struct {
  external ffi.Pointer<ffi.Void> t;

  external ffi.Pointer<ffi.Void> v;
}

final class GoSlice extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @GoInt()
  external int len;

  @GoInt()
  external int cap;
}

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int _WCHAR_T_DEFINED = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_CXX23 = 0;

const int _HAS_CXX26 = 0;

const int _HAS_NODISCARD = 1;

const int _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE = 1;

const int _CRT_BUILD_DESKTOP_APP = 1;

const int _UCRT_DISABLED_WARNINGS = 4324;

const int _ARGMAX = 100;

const int _TRUNCATE = -1;

const int _CRT_INT_MAX = 2147483647;

const int _CRT_SIZE_MAX = -1;

const String __FILEW__ = 'C';

const int _CRT_FUNCTIONS_REQUIRED = 1;

const int _CRT_HAS_CXX17 = 0;

const int _CRT_HAS_C11 = 0;

const int _CRT_INTERNAL_NONSTDC_NAMES = 1;

const int __STDC_SECURE_LIB__ = 200411;

const int __GOT_SECURE_LIB__ = 200411;

const int __STDC_WANT_SECURE_LIB__ = 1;

const int _SECURECRT_FILL_BUFFER_PATTERN = 254;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = 0;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES = 1;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY = 0;

const int _STATIC_INLINE_UCRT_FUNCTIONS = 0;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -2147483648;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 2147483647;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 4294967295;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WCHAR_MIN = 0;

const int WCHAR_MAX = 65535;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;
